language: cpp
sudo: required
distribution: trusty

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      #- boost-latest
    packages:
      - gcc-6
      - g++-6
      #- libboost-all-dev


os:
- linux
- osx
env:
- BADGE=linux
- BADGE=osx
matrix:
  exclude:
    - os: linux
      env: BADGE=osx
    - os: osx
      env: BADGE=linux

compiler:
- gcc
- clang

before_install:
- export LD_LIBRARY_PATH=/usr/local/clang/lib:$LD_LIBRARY_PATH

script:
- sudo ln -s /usr/bin/gcc-6 /usr/local/bin/gcc
- sudo ln -s /usr/bin/g++-6 /usr/local/bin/g++
- wget https://dl.bintray.com/boostorg/release/1.69.0/source/boost_1_69_0.tar.gz
- tar -zxf boost_1_69_0.tar.gz
- sudo cp -r ./boost_1_69_0/boost /usr/local/include/
- cd build
- cmake -DCMAKE_BUILD_TYPE=Release ..
- make clean
- make
- make test
- ./example
